### ISSUE TITLE
Error in Readme of level 3

### ISSUE THREAD

**Issue by carlosipe** [drivy/jobs#1]
In https://github.com/drivy/jobs/blob/master/backend/level3/README.md says:
- 1€/day goes to the roadside assistance

Reading the output in https://github.com/drivy/jobs/blob/master/backend/level3/output.json , it is clear that it should be:

- 100€/day goes to the roadside assistance

**Comment by nmondollot** [comment]
it's a feature, not a bug
https://github.com/drivy/jobs/tree/master/backend#things-to-know

cheers

**Comment by carlosipe** [comment]
Thanks!
